using Test
using NoLimits

# Shared model/fit fixtures (built once, reused by every test below) — see
# fixtures.jl. The suite runs as a single flat sequence so each canonical model
# is compiled once and each method is fit once.
include("fixtures.jl")

# Each file runs inside its own @testset so a top-level error in one file is
# recorded as a failure rather than aborting the whole suite. `include` still
# evaluates each file in this module's global scope.
const TEST_FILES = [
    "softtrees_tests.jl",
    "ad_softtree.jl",
    "ad_flow.jl",
    "ad_random_effects.jl",
    "ad_random_effects_values.jl",
    "ad_fixed_prede.jl",
    "ad_differential_equation.jl",
    "ad_ode_solve_basic.jl",
    "ad_ode_solve_richer.jl",
    "ad_misc.jl",
    "ad_model_full.jl",
    "helpers_tests.jl",
    "parameters_tests.jl",
    "transform_tests.jl",
    "fixed_effects_tests.jl",
    "splines_tests.jl",
    "covariates_tests.jl",
    "random_effects_tests.jl",
    "prede_tests.jl",
    "differential_equation_tests.jl",
    "ode_solve_tests.jl",
    "formulas_tests.jl",
    "initialde_tests.jl",
    "model_macro_tests.jl",
    "model_tests.jl",
    "equation_display_tests.jl",
    "data_model_tests.jl",
    "identifiability_tests.jl",
    "data_model_ode_tests.jl",
    "summaries_data_model_tests.jl",
    "summaries_model_tests.jl",
    "summaries_fit_uq_tests.jl",
    "summaries_parameter_comparison_tests.jl",
    "compact_show_tests.jl",
    "data_simulation_tests.jl",
    "ode_callbacks_tests.jl",
    "plot_cache_tests.jl",
    "plotting_functions_tests.jl",
    "vpc_tests.jl",
    "plot_observation_distributions_tests.jl",
    "residual_plots_tests.jl",
    "plot_random_effects_tests.jl",
    "random_effect_new_plots_tests.jl",
    "re_covariate_usage_tests.jl",
    "estimation_common_tests.jl",
    "integration_no_re.jl",
    "integration_simple_re.jl",
    "integration_plotting.jl",
    "estimation_mcmc_tests.jl",
    "estimation_mcmc_re_tests.jl",
    "estimation_laplace_tests.jl",
    "estimation_focei_tests.jl",
    "estimation_pooled_tests.jl",
    "estimation_hutchinson_tests.jl",
    "estimation_mcem_tests.jl",
    "estimation_mcem_is_tests.jl",
    "estimation_saem_tests.jl",
    "saem_options_unit_tests.jl",
    "saem_adaptive_mh_tests.jl",
    "estimation_saem_autodetect_tests.jl",
    "estimation_saem_suffstats_tests.jl",
    "saem_saemixmh_tests.jl",
    "estimation_multistart_tests.jl",
    "estimation_ghquadrature_tests.jl",
    "uq_tests.jl",
    "uq_edge_cases_tests.jl",
    "uq_plotting_tests.jl",
    "hmm_continuous_tests.jl",
    "hmm_discrete_time_tests.jl",
    "hmm_estimation_method_matrix_tests.jl",
    "hmm_mv_discrete_tests.jl",
    "hmm_mv_continuous_tests.jl",
    "stickbreak_parameter_tests.jl",
    "stickbreak_transform_tests.jl",
    "stickbreak_uq_tests.jl",
    "stickbreak_uq_natural_extension_tests.jl",
    "ad_stickbreak_hmm.jl",
    "continuous_transition_matrix_tests.jl",
    "datasets_tests.jl",
    "accessors_tests.jl",
    "estimation_mle_tests.jl",
    "estimation_map_tests.jl",
    "estimation_vi_tests.jl",
    "estimation_cv_tests.jl",
    "markov_discrete_time_tests.jl",
    "markov_continuous_time_tests.jl",
    "saem_schedule_tests.jl",
    "saem_multichain_tests.jl",
    "saem_sa_anneal_tests.jl",
    "saem_var_lb_tests.jl",
    "saem_anneal_ebe_tests.jl",
    "saem_mstep_sa_on_params_tests.jl",
    "logit_scale_parameter_tests.jl",
    "logit_scale_transform_tests.jl",
    "logit_scale_uq_tests.jl",
    "serialization_tests.jl",
    "coverage_gap_tests.jl",
]

@testset "NoLimits" begin
    for f in TEST_FILES
        @testset "$f" begin
            include(f)
        end
    end
end
